### ISSUE TITLE
scrypt_hash doesn't actually use scrypt. 

### ISSUE THREAD

**Issue by jdbernard** [FedericoCeratto/nim-httpauth#23]
Looking at the implementation of `scrypt_hash` it looks like we do not actually hash the cleartext.

https://github.com/FedericoCeratto/nim-httpauth/blob/master/httpauth.nim#L116

**Comment by FedericoCeratto** [comment]
Thank you @jdbernard , it appears work-in-progess code was merged by mistake. I'll make a new release shortly.
